GET http://localhost:5001/karyawan
###
GET http://localhost:5001/plafond/PL003

###
# POST http://localhost:5001/antrean
# Content-Type: application/json

# {
#     "id_pinjaman": "P00003"
# }


###
POST http://localhost:5001/plafond-update
Content-Type: application/json

{
    "tanggal_plafond_tersedia": 2025-01-13,
    "plafond_saat_ini": 8300000, 
    "id_pinjaman": "P000012", 

}


###m 
GET http://localhost:5001/plafond/latest-id 

